version: '3'
services:
  consul:
    container_name: blueprint_Consul
    image: "consul:latest"
    hostname: "consul"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    networks:
      - blueprint_default

      
  postgres:
    container_name: PostgresDB
    image: "postgres:latest"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

      
  api:
    container_name: blueprint
    build: .
    ports:
      - "5500:8888"
    environment:
      SPRING_CLOUD_CONSUL_HOST: "consul"
    networks:
      - blueprint_default
    depends_on:
      - 'consul'
networks:
  blueprint_default:
    external:
      name: blueprint_default

