spring:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/emdm_d
    username: tdaruwalla
    password: tdaruwalla
    driver-class-name: org.postgresql.Driver
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-interval: 100s
  jpa:
    show-sql: true
    database-platform: com.corvesta.keyspring.blueprint.utils.JsonbExtensionToPostgreSQLDialect
    properties:
      hibernate:
        default_schema: emdm
        ddl-auto: create-drop
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  application:
    name: Blueprint-Service
logging:
  level:
    root: fatal
    com.corvesta: debug
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  file: /tmp/config/logs/blueprint-service.log
server:
  port: 8888
management:
  endpoint:
    health:
      enabled: true
      show-details: always
swagger:
  api:
    base:
      package: com.dc.blueprint.api
    path: /*
    title: Blueprint REST API
    description: Spring Boot REST API for Blueprint
    version: 1.0
    termsofservice:
      url: Terms of service
    contact:
      name: DC
      url: https://github.com/dwai1714/blueprint
      email: dwaip@yahoo.com
    license:
      name: null
      url: null
oracle:
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    jdbcUrl: jdbc:oracle:thin:@localhost:1521:xe
    username: scott
    password: tiger
resource.id: blueprint



keycloak-client.id: SpringBootKeycloak
keycloak-client.name: SpringBootKeycloak
keycloak-client.secret: 3a816bde-3130-4241-87c2-aeeffb715855
keycloak.auth-server-url: http://localhost:8180/auth
keycloak.realm: master
keycloak.resource: SpringBootKeycloak
keycloak.public-client: true
keycloak.principal-attribute: preferred_username
keycloak-client.scopes: openid, profile
keycloak.jwk: http://localhost:8180/auth/realms/master/protocol/openid-connect/certs
keycloak.issuer: http://localhost:8180/auth/realms/master  